# Stage 1: Build & Development Environment
FROM golang:1.25-alpine AS dev_builder

WORKDIR /app

COPY go.mod go.sum .air.toml ./
RUN go mod download && go install github.com/air-verse/air@latest
# airを実行。カレントディレクトリに.air.tomlがあることを想定
# 開発時にはソースコードがコンテナにマウントされる
CMD ["air", "-c", ".air.toml"]
